name: Release

on:
  push:
    tags: "*"

jobs:
  build:
    runs-on: ubuntu-latest
    concurrency:
      group: ${{ github.workflow }}-${{ github.ref }}
      cancel-in-progress: true
    steps:
      - uses: actions/checkout@v3

      - uses: pnpm/action-setup@v2.2.4
        with:
          version: latest

      - uses: actions/setup-node@v3
        with:
          node-version: 18
          cache: "pnpm"

      - run: |
          pnpm install
          pnpm run build

      - uses: papeloto/action-zip@v1
        with:
          files: dist
          dest: dist.zip

      - uses: softprops/action-gh-release@v1
        with:
          files: dist.zip
